service: serverless-tutorial

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  versionFunctions: false
  lambdaHashingVersion: 20201221
  memorySize: 128
  region: ap-northeast-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "S3:*"
          Resource:
            - "*"

functions:
  hello:
    handler: handler.hello
    events:
      - s3:
          bucket: photos20220120
          event: s3:ObjectCreated:*
